spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: wcjb
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.zjt.pojo